apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: allconnect
data:
  # Database
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "allconnect"

  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"

  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"

  # Eureka
  EUREKA_SERVER_URL: "http://eureka-service:8761/eureka"

  # Gateway
  GATEWAY_URL: "http://gateway-service:8080"

  # Services URLs (internal)
  ORDER_SERVICE_URL: "http://order-service:8090"
  CATALOG_SERVICE_URL: "http://catalog-service:8091"
  CUSTOMER_SERVICE_URL: "http://customer-service:8092"
  PAYMENT_SERVICE_URL: "http://payment-service:8093"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8094"
  INTEGRATION_SERVICE_URL: "http://integration-service:8095"
