apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: allconnect
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "allconnect_root_2025"
  MYSQL_USER: "allconnect_user"
  MYSQL_PASSWORD: "allconnect_pass_2025"
