apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: allconnect
type: Opaque
stringData:
  JWT_SECRET: "allconnect-jwt-secret-key-2025-very-secure-random-string"
  JWT_EXPIRATION: "86400000"
